- hosts: localhost
  vars:
    basic:
      - zsh
      - tmux
      - vim
    advanced:
      - git
      - htop
      - cmake
      - wget
      - ripgrep
      - nodejs
      - python3
    pip:
      - powerline-status
      - tmuxp
      - thefuck
    npm:
      - fkill
      - tldr
      - git-standup
  roles:
    - install
  tags:
    - install
  
- hosts: localhost
  roles:
    - symlink
  tags:
    - symlink