- name: prepare dirs
  file:
    path: "~/.{{ item }}"
    state: directory
  loop:
    - vim
    - config

- name: symlink files
  file:
    src: "~/.terminal/roles/symlink/files/{{ item }}"
    dest: "~/.{{ item }}"
    state: link
    force: true
  loop:
    - tmux.conf
    - zshrc
    - vimrc
    - vim/config
    - config/powerline

- name: turn off solarized
  lineinfile:
    path: ~/.vimrc
    regexp: 'source ~/.vim/config/solarized.vim'
    line: '" source ~/.vim/config/solarized.vim'

- name: install vim plugin
  shell: vim +PlugInstall +qa

- name: turn on solarized
  lineinfile:
    path: ~/.vimrc
    regexp: '" source ~/.vim/config/solarized.vim'
    line: 'source ~/.vim/config/solarized.vim'

- name: symlink vim colors
  file:
    src: ~/.vim/plugged/vim-colors-solarized/colors
    dest: ~/.vim/colors
    state: link