- name: install cnpm
  ignore_errors: True
  shell: npm install -g cnpm --registry=https://registry.npm.taobao.org

- name: install node.js packages
  ignore_errors: True
  become: true
  shell: cnpm install -g {{ item }}
  with_items:
    "{{ npm }}"